name: Nix lint and format

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Flake check
        run: nix flake check ./nix

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting
        run: find nix/ -name '*.nix' | xargs nix run nixpkgs#nixfmt -- --check

  deadnix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Find unused code
        run: nix run nixpkgs#deadnix -- --fail nix/

  statix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check for anti-patterns
        run: nix run nixpkgs#statix -- check nix/
